GET http://localhost:3000/
###
POST http://localhost:3000/profile/
###
GET  http://localhost:3000/api/auth/other
### Register

POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "email": "resClient@gmail.com",
   "fullname":"Restlong Yu",
    "password": "1029384756"
}
### Login

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "resClient@gmail.com",
    "password": "1029384756"
}

### Logout

GET  http://localhost:3000/auth/logout 
